@startuml 

package "MusiCode Editor" {
    component [IDE]
    component [App Backend]
}
interface "End User"
node "Transpiler" {
    component [MusiCode Lexer/Parser]
    component [Tree Transformer]
    component [LilyPond Printer]
}
component [LilyPond Tools]

[End User] -u-> [IDE] : MusiCode
[IDE] -> [App Backend] : MusiCode
[End User] --> [App Backend] : Compile Request
[App Backend] --> [End User] : Generated Score & MIDI 

[App Backend] --> [MusiCode Lexer/Parser] : MusiCode
[MusiCode Lexer/Parser] ..> [IDE] : Error Messages
[MusiCode Lexer/Parser] --> [Tree Transformer] : MusiCode AST 
[Tree Transformer] --> [LilyPond Printer] : Intermediate Representation
[LilyPond Printer] --> [LilyPond Tools] : LilyPond 

[LilyPond Tools] --> [App Backend] : Score PDF, MIDI Audio 

@enduml