mc_to_lily_pre_note_modifiers = {
    "stemUp" : "\\stemUp",
    "stemDown" : "\\stemDown",
    "beamStemLeftCount0" : "\n\\set stemLeftBeamCount = #0\n",
    "beamStemLeftCount1" : "\n\\set stemLeftBeamCount = #1\n",
    "beamStemLeftCount2" : "\n\\set stemLeftBeamCount = #2\n",
    "beamStemLeftCount3" : "\n\\set stemLeftBeamCount = #3\n",
    "beamStemLeftCount4" : "\n\\set stemLeftBeamCount = #4\n",
    "beamStemLeftCount5" : "\n\\set stemLeftBeamCount = #5\n",
    "beamStemRightCount0" : "\n\\set stemRightBeamCount = #0\n",
    "beamStemRightCount1" : "\n\\set stemRightBeamCount = #1\n",
    "beamStemRightCount2" : "\n\\set stemRightBeamCount = #2\n",
    "beamStemRightCount3" : "\n\\set stemRightBeamCount = #3\n",
    "beamStemRightCount4" : "\n\\set stemRightBeamCount = #4\n",
    "beamStemRightCount5" : "\n\\set stemRightBeamCount = #5\n"
}

mc_to_lily_post_note_modifiers = {
    "tie" : "~",
    "gliss" : "\\glissando",
    "slurBegin" : "(",
    "slurEnd" : ")",
    "phrasingSlurBegin" : "\\(",
    "phrasingSlurEnd" : "\\)",
    "tremolo8" : ":8",
    "tremolo16" : ":16",
    "tremolo32" : ":32",
    
    "pedalBegin" : "\\sustainOn",
    "pedalLift" : "\\sustainOff\\sustainOn",
    "pedalEnd" : "\\sustainOff",
    "pianoFinger1" : "-1",
    "pianoFinger2" : "-2",
    "pianoFinger3" : "-3",
    "pianoFinger4" : "-4",
    "pianoFinger5" : "-5",
    
    "crescBegin" : "\\<",
    "crescendoBegin" : "\\<",
    "crescEnd" : "\\!",
    "crescendoEnd" : "\\!",
    "decrescBegin" : "\\>",
    "decrescendoBegin" : "\\>",
    "decrescEnd" : "\\!",
    "decrescendoEnd" : "\\!",
    "dimBegin" : "\\>",
    "diminuendoBegin" : "\\>",
    "dimEnd" : "\\!",
    "diminuendoEnd" : "\\!",

    "crescTextBegin" : "\\cresc",
    "crescendoTextBegin" : "\\cresc",
    "crescTextEnd" : "\\!",
    "crescendoTextEnd" : "\\!",
    "decrescTextBegin" : "\\decresc",
    "decrescendoTextBegin" : "\\decresc",
    "decrescTextEnd" : "\\!",
    "decrescendoTextEnd" : "\\!",
    "dimTextBegin" : "\\decresc",
    "diminuendoTextBegin" : "\\decresc",
    "dimTextEnd" : "\\!",
    "diminuendoTextEnd" : "\\!",

    "beamNone" : "\\noBeam",
    "beamBegin" : "[",
    "beamBeginUp" : "^[",
    "beamBeginDown" : "_[",
    "beamEnd" : "]",

    # Empty strings because these are taken care of BEFORE the note
    "beamStemLeftCount0" : "",
    "beamStemLeftCount1" : "",
    "beamStemLeftCount2" : "",
    "beamStemLeftCount3" : "",
    "beamStemLeftCount4" : "",
    "beamStemLeftCount5" : "",
    "beamStemRightCount0" : "",
    "beamStemRightCount1" : "",
    "beamStemRightCount2" : "",
    "beamStemRightCount3" : "",
    "beamStemRightCount4" : "",
    "beamStemRightCount5" : "",

    # Stem neutral to reset stemming environment after the note 
    "stemUp" : "\\stemNeutral",
    "stemDown" : "\\stemNeutral"
}

instr_to_short_instr = {
    "Piccolo" : "Picc.",
    "Flute" : "Fl.",
    "Oboe" : "Ob.",
    "English Horn" : "E. H.",
    "Clarinet" : "Cl.",
    "Bass Clarinet" : "B. Cl.",
    "Bassoon" : "Bsn.",
    "Double Bassoon" : "D. Bsn.",
    "Contrabassoon" : "C. bsn.",
    "Horn" : "Hn.",
    "French Horn" : "Hn.",
    "Cornet" : "Cor.",
    "Trumpet" : "Tpt.",
    "Trombone" : "Tbn.",
    "Tuba" : "Tb.",
    "Triangle" : "Trgl.",
    "Cymbals" : "Cym.",
    "Bass drum" : "B. d.",
    "Snare drum" : "S. d.",
    "Tambourine" : "Tamb.",
    "Castanets" : "Cast.",
    "Gong" : "Gng.",
    "Tubular bells" : "T. b.",
    "Chimes" : "T. b.",
    "Glockenspiel" : "Glock.",
    "Xylophone" : "Xyl.",
    "Celesta" : "Cel.",
    "Piano" : "Pno.",
    "Harp" : "Hp.",
    "Violin" : "Vln.",
    "Viola" : "Vla.",
    "Violoncello" : "Vc.",
    "Cello" : "Vc.",
    "Double bass" : "D. B.",
    "Guitar" : "Gui."
}

grand_staffs = [
    "Piano",
    "Electric Piano",
    "Keyboard",
    "Harp",
    "Harpsichord",
    "Accordion",
    "Celesta",
    "Organ"
]